gazebo_ros_control:
  pid_gains:
    ur5e_shoulder_pan_joint:
      p: 5.0
      i: 0.05
      d: 0.1
      i_clamp: 1

    ur5e_shoulder_lift_joint:
      p: 5.0
      i: 1.0
      d: 0.1
      i_clamp: 1

    ur5e_elbow_joint:
      p: 5.0
      i: 0.05
      d: 0.1
      i_clamp: 1

    ur5e_wrist_1_joint:
      p: 5.0
      i: 0.05
      d: 0.1
      i_clamp: 1

    ur5e_wrist_2_joint:
      p: 5.0
      i: 0.05
      d: 0.1
      i_clamp: 1

    ur5e_wrist_3_joint:
      p: 5.0
      i: 0.05
      d: 0.1
      i_clamp: 1

    finger_joint:
      p: 5.0
      i: 0.05
      d: 0.1
      i_clamp: 1

    
