left_gripper_position_controller:
  type: position_controllers/JointPositionController
  joint: finger_joint
right_gripper_position_controller:
  type: position_controllers/JointPositionController
  joint: right_outer_knuckle_joint